/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.service.impl;

import java.util.Collection;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Function;
import javax.annotation.Resource;

import org.springframework.beans.factory.annotation.Value;
import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.ServiceUtil;
import org.stategen.framework.util.StringUtil;

import ${packageName}.dao.FileSummaryDao;
import ${packageName}.domain.FileSummary;
import ${packageName}.service.FileSummaryService;

/**
 * FileSummaryServiceImpl
 * <pre>
 * database table: upload_file
 * database table comments: FileSummary
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class FileSummaryServiceImpl implements FileSummaryService {

    @Value("${'${'}project.name}")
    private String projectName;



    @Override
    public String getProjectName() {
        return projectName;
    }
}
