/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignService;

import ${packageName}.domain.Menu;
import ${packageName}.domain.Role;

/**
 * RoleServiceFacade
 * <pre>
 * database table: role
 * database table comments: Role
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface RoleService extends AssignService<Role, String>, RoleService${systemName?cap_first} {

    public List<Menu> getAllMenusWithRoleChecked(String roleId);
	

}
