/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignService;

import ${packageName}.domain.Menu;

/**
 * MenuServiceFacade
 * <pre>
 * database table: visit
 * database table comments: IMenu
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface MenuService extends AssignService<Menu, Long>, MenuService${systemName?cap_first} {

    String getProjectName();

    public List<Menu> updateMenus(List<Menu> allControllerMenus);

    public List<Menu> getAllMenus();


}
