/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service.impl;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.BiConsumer;
import java.util.function.Function;
import javax.annotation.Resource;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.util.LinkedCaseInsensitiveMap;
import org.stategen.framework.lite.PageList;
import org.stategen.framework.lite.enums.MenuType;
import org.stategen.framework.util.CollectionUtil;
import org.stategen.framework.util.StringUtil;

import ${packageName}.dao.MenuDao;
import ${packageName}.domain.Menu;
import ${packageName}.service.MenuService;

/**
 * MenuServiceImpl
 * <pre>
 * database table: visit
 * database table comments: IMenu
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class MenuServiceImpl implements MenuService {

    @Value("${'${'}project.name}")
    private String projectName;

    @Resource(name = "menuDao")
    MenuDao menuDao;

    private class VisitKeyCalculator implements CollectionUtil.KeyCalculator<String, Menu> {

        @Override
        public String calculateKey(Menu menu) {
            String result = new StringBuffer().append(menu.getControllerName()).append('.').append(menu.getMethodName()).toString();
            return result;
        }
    }

    private void insertOrUpdateMenus(Long parentMenuId, List<Menu> menus, Map<String, Menu> oldMenuMap, VisitKeyCalculator visitKeyCalculator) {
        if (CollectionUtil.isNotEmpty(menus)) {
            for (Menu menu : menus) {
                menu.setMpid(parentMenuId);
                menu.setProjectName(projectName);
                menu.setDeleteFlag(0);
                String key = visitKeyCalculator.calculateKey(menu);
                Menu oldMenu = oldMenuMap.get(key);
                if (oldMenu != null) {
                    menu.setMenuId(oldMenu.getMenuId());
                    this.forceUpdateById(menu);
                } else {
                    this.insert(menu);
                }
                insertOrUpdateMenus(menu.getMenuId(), menu.getMenuChildren(), oldMenuMap, visitKeyCalculator);
            }
        }
    }

    @Override
    public List<Menu> updateMenus(List<Menu> allControllerMenus) {
        //更新visitId
        VisitKeyCalculator visitKeyCalculator = new VisitKeyCalculator();
        List<Menu> oldMenus = this.getMenusByProjectName(getProjectName(), null);
        Map<String, Menu> oldMenuMap = CollectionUtil.toMap(new LinkedCaseInsensitiveMap<Menu>(), visitKeyCalculator, oldMenus);
        Long parentMenuId = null;
        this.insertOrUpdateMenus(parentMenuId, allControllerMenus, oldMenuMap, visitKeyCalculator);
        return allControllerMenus;
    }

    @Override
    public String getProjectName() {
        return projectName;
    }

    @Override
    public List<Menu> getAllMenus() {
        return this.getMenusByProjectName(getProjectName(), MenuType.MENU);
    }
	
    //<#--

    /**
     * 
     * @see ${packageName}.dao.MenuDao#insert
     * @see ${packageName}.service.MenuService#insert
     */
    @Override
    public Menu insert(Menu menu) {
        return menuDao.insert(menu);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#update
     * @see ${packageName}.service.MenuService#update
     */
    @Override
    public Menu update(Menu menu) {
        return menuDao.update(menu);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#getMenuByMenuId
     * @see ${packageName}.service.MenuService#getMenuByMenuId
     */
    @Override
    public Menu getMenuByMenuId(Long menuId) {
        return menuDao.getMenuByMenuId(menuId);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#getMenusByMenuIds
     * @see ${packageName}.service.MenuService#getMenusByMenuIds
     */
    @Override
    public List<Menu> getMenusByMenuIds(java.util.List<Long> menuIds) {
        return menuDao.getMenusByMenuIds(menuIds);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#deleteByMenuIds
     * @see ${packageName}.service.MenuService#deleteByMenuIds
     */
    @Override
    public List<Long> deleteByMenuIds(java.util.List<Long> menuIds) {
        return menuDao.deleteByMenuIds(menuIds);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#getMenusByUserId
     * @see ${packageName}.service.MenuService#getMenusByUserId
     */
    @Override
    public List<Long> getMenusByUserId(String userId, org.stategen.framework.lite.enums.MenuType menuType) {
        return menuDao.getMenusByUserId(userId, menuType);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#forceUpdateById
     * @see ${packageName}.service.MenuService#forceUpdateById
     */
    @Override
    public Long forceUpdateById(Menu menu) {
        return menuDao.forceUpdateById(menu);
    }

    /*** 保存menu,有id时更新，没有id时插入,并带回新的id，返回 menu*/
    @Override
    public Menu saveMenu(Menu menu) {
        if (menu != null) {
            java.lang.Long menuId = menu.getMenuId();
            if (menuId != null) {
                insert(menu);
            } else {
                update(menu);
            }
        }
        return menu;
    }

    /*** 批量保存menus,有id时更新，没有id时插入,并带回新的id，返回 menus*/
    @Override
    public List<Menu> saveMenus(List<Menu> menus) {
        for (Menu menu : menus) {
            this.saveMenu(menu);
        }
        return menus;
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#delete
     * @see ${packageName}.service.MenuService#delete
     */
    @Override
    public Long delete(Long menuId) {
        return menuDao.delete(menuId);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#getMenuPageList
     * @see ${packageName}.service.MenuService#getMenuPageList
     */
    @Override
    public PageList<Menu> getMenuPageList(Menu menu, int pageSize, int pageNum) {
        return menuDao.getMenuPageList(menu, pageSize, pageNum);
    }

    /**
     * 
     * @see ${packageName}.dao.MenuDao#getMenusByProjectName
     * @see ${packageName}.service.MenuService#getMenusByProjectName
     */
    @Override
    public List<Menu> getMenusByProjectName(String projectName, org.stategen.framework.lite.enums.MenuType menuType) {
        return menuDao.getMenusByProjectName(projectName, menuType);
    }


    //-->
    //
}
