/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.service.impl;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.BiConsumer;
import java.util.function.Function;
import javax.annotation.Resource;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.CollectionUtil;
import org.stategen.framework.util.StringUtil;

import ${packageName}.dao.TopicReplyDao;
import ${packageName}.domain.TopicReply;
import ${packageName}.domain.TopicUp;
import ${packageName}.domain.User;
import ${packageName}.service.FileSummaryService;
import ${packageName}.service.TopicReplyService;
import ${packageName}.service.TopicUpService;
import ${packageName}.service.UserService;

/**
 * TopicReplyServiceImpl
 * <pre>
 * database table: topic_reply
 * database table comments: TopicReply
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class TopicReplyServiceImpl implements TopicReplyService {

    @Resource
    TopicUpService topicUpService;

    @Resource
    UserService userService;

    @Resource
    FileSummaryService fileSummaryService;

    @Override
    public void assignRepliesExtraProperties(String authorId, List<TopicReply> replies) {
        userService.assignBeanTo(replies, TopicReply::getAuthorId, TopicReply::setAuthor);
        List<User> authors = CollectionUtil.toList(replies, TopicReply::getAuthor);
        fileSummaryService.assignBeanTo(authors, User::getAvatarImgId, User::setAvatarImg);
        List<String> replyIds = CollectionUtil.toList(replies, TopicReply::getReplyId);
        List<TopicUp> topicUpCounts = this.topicUpService.getTopicUpsGroupCountByTopicIds(replyIds, null);
        Map<String, TopicUp> upCountMap = CollectionUtil.toMap(topicUpCounts, TopicUp::getObjectId);
        CollectionUtil.setFeildToFieldByMap(replies, upCountMap, TopicReply::getReplyId, TopicReply::setUpCount, TopicUp::getUpCount);
        if (StringUtil.isNotEmpty(authorId)) {
            topicUpCounts = this.topicUpService.getTopicUpsGroupCountByTopicIds(replyIds, authorId);
            upCountMap = CollectionUtil.toMap(topicUpCounts, TopicUp::getObjectId);
            for (TopicReply tr : replies) {
                tr.setIsUped(upCountMap.containsKey(tr.getReplyId()));
            }
        }
    }

    @Override
    public TopicReply replyUp(String replyId, String authorId) {
        List<TopicUp> topicUps = this.topicUpService.getTopicUpByObjectIdAndAuthorId(replyId, authorId);
        if (CollectionUtil.isNotEmpty(topicUps)) {
            topicUpService.deleteByUpIds(CollectionUtil.toList(topicUps, TopicUp::getUpId));
        } else {
            TopicUp topicUp = new TopicUp();
            topicUp.setObjectId(replyId);
            topicUp.setAuthorId(authorId);
            this.topicUpService.insert(topicUp);
        }
        TopicReply topicReply = this.getTopicReplyByReplyId(replyId);
        return topicReply;
    }

    //<#--
    @Resource(name = "topicReplyDao")
    TopicReplyDao topicReplyDao;

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#insert
     * @see ${packageName}.service.TopicReplyService#insert
     */
    @Override
    public TopicReply insert(TopicReply topicReply) {
        return topicReplyDao.insert(topicReply);
    }

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#delete
     * @see ${packageName}.service.TopicReplyService#delete
     */
    @Override
    public String delete(String replyId) {
        return topicReplyDao.delete(replyId);
    }

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#update
     * @see ${packageName}.service.TopicReplyService#update
     */
    @Override
    public TopicReply update(TopicReply topicReply) {
        return topicReplyDao.update(topicReply);
    }

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#getTopicReplyByReplyId
     * @see ${packageName}.service.TopicReplyService#getTopicReplyByReplyId
     */
    @Override
    public TopicReply getTopicReplyByReplyId(String replyId) {
        return topicReplyDao.getTopicReplyByReplyId(replyId);
    }

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#getTopicReplysByReplyIds
     * @see ${packageName}.service.TopicReplyService#getTopicReplysByReplyIds
     */
    @Override
    public List<TopicReply> getTopicReplysByReplyIds(java.util.List<String> replyIds) {
        return topicReplyDao.getTopicReplysByReplyIds(replyIds);
    }

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#deleteByReplyIds
     * @see ${packageName}.service.TopicReplyService#deleteByReplyIds
     */
    @Override
    public java.util.List<String> deleteByReplyIds(java.util.List<String> replyIds) {
        return topicReplyDao.deleteByReplyIds(replyIds);
    }

    /*** 保存topicReply,有id时更新，没有id时插入,并带回新的id，返回 topicReply*/
    @Override
    public TopicReply saveTopicReply(TopicReply topicReply) {
        if (topicReply != null) {
            java.lang.String replyId = topicReply.getReplyId();
            if (StringUtil.isBlank(replyId)) {
                insert(topicReply);
            } else {
                update(topicReply);
            }
        }
        return topicReply;
    }

    /*** 批量保存topicReplys,有id时更新，没有id时插入,并带回新的id，返回 topicReplys*/
    @Override
    public List<TopicReply> saveTopicReplys(List<TopicReply> topicReplys) {
        for (TopicReply topicReply : topicReplys) {
            this.saveTopicReply(topicReply);
        }
        return topicReplys;
    }

    /**
     * 
     * @see ${packageName}.dao.TopicReplyDao#getTopicReplyPageList
     * @see ${packageName}.service.TopicReplyService#getTopicReplyPageList
     */
    @Override
    public PageList<TopicReply> getTopicReplyPageList(TopicReply topicReply, int pageSize, int pageNum) {
        PageList<TopicReply> topicReplyList = topicReplyDao.getTopicReplyPageList(topicReply, pageSize, pageNum);
        return topicReplyList;
    }

    @Override
    public <D> void assignBeanTo(Collection<D> dests, Function<? super D, String> destGetMethod, BiConsumer<D, TopicReply> destSetMethod) {
        if (CollectionUtil.isNotEmpty(dests)) {
            Set<String> replyIds = CollectionUtil.toSet(dests, destGetMethod);
            List<TopicReply> topicReplys = this.getTopicReplysByReplyIds(new ArrayList<String>(replyIds));
            if (CollectionUtil.isNotEmpty(topicReplys)) {
                CollectionUtil.setModelByList(dests, topicReplys, destGetMethod, destSetMethod, TopicReply::getReplyId);
            }
        }
    }
    //-->
    //
}
