/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.dao;

import java.util.List;

import ${packageName}.domain.Role;
import org.springframework.dao.DataAccessException;
import org.stategen.framework.lite.PageList;

/**
 * RoleDao
 * <pre>
 * database table: role
 * database table comments: Role
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅可以修改引用
 * </pre>
 */
public interface RoleDao {

	/**
    <pre>
    &#64;ApiParam() String roleId,
    &#64;ApiParam() String roleName,
    &#64;ApiParam() String description,
    &#64;ApiParam() RoleType roleType,
    &#64;ApiParam(hidden = true) Role role,
    
    </pre>
	 * 
	 * sql:insert into role ( create_time , update_time , delete_flag , role_id , role_name , description , role_type ) VALUES (CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),0,?,?,?,?)
	 */
	public Role insert(Role role) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("角色ID") String roleId,
    
    </pre>
	 * 
	 * sql:UPDATE role SET delete_flag = 1 , update_time = CURRENT_TIMESTAMP(6) where delete_flag = 0 and role_id = ?
	 */
	public String delete(String roleId) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam() String roleName,
    &#64;ApiParam() String description,
    &#64;ApiParam() RoleType roleType,
    &#64;ApiParam() String roleId,
    &#64;ApiParam(hidden = true) Role role,
    
    </pre>
	 * 
	 * sql:UPDATE role SET update_time= CURRENT_TIMESTAMP(6) , role_name = ? , description = ? , role_type = ? where delete_flag = 0 and role_id = ?
	 */
	public Role update(Role role) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("角色ID") String roleId,
    
    </pre>
	 * 
	 * sql:select a.role_id, a.role_name, a.description, a.create_time, a.update_time, a.delete_flag, a.role_type from role a where a.delete_flag = 0 and a.role_id = ?
	 */
	public Role getRoleByRoleId(String roleId) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam()&#64;RequestParam(required =false,name="roleIds") ArrayList&lt;String&gt; roleIds,
    &#64;ApiParam() String roleNameLike,
    &#64;ApiParam() String descriptionLike,
    &#64;ApiParam() Date createTimeMin,
    &#64;ApiParam() Date createTimeMax,
    &#64;ApiParam() Date updateTimeMin,
    &#64;ApiParam() Date updateTimeMax,
    &#64;ApiParam()&#64;RequestParam(required =false,name="roleTypes") ArrayList&lt;RoleType&gt; roleTypes,
    &#64;ApiParam(hidden = true) Role role,
    &#64;ApiParam(hidden = true) Pagination pagination
    </pre>
	 * 
	 * sql:select a.role_id, a.role_name, a.description, a.create_time, a.update_time, a.delete_flag, a.role_type from role a where a.delete_flag = 0 and a.role_id in ( ? ) and a.role_name like CONCAT('%',?,'%') and a.description like CONCAT('%',?,'%') and a.create_time >=? and a.create_time <? and a.update_time >=? and a.update_time <? and a.role_type in ( ? ) and 0 = 1
	 */
	public PageList<Role> getRolePageListByDefaultQuery(Role role, int pageSize, int pageNum) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("角色ID")&#64;RequestParam(required =false,name="roleIds") ArrayList&lt;String&gt; roleIds,
    
    </pre>
	 * 
	 * sql:select a.role_id, a.role_name, a.description, a.create_time, a.update_time, a.delete_flag, a.role_type from role a where a.delete_flag = 0 and a.role_id in ( ? )
	 */
	public List<Role> getRolesByRoleIds(java.util.List<String> roleIds) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("角色ID")&#64;RequestParam(required =false,name="roleIds") ArrayList&lt;String&gt; roleIds,
    
    </pre>
	 * 
	 * sql:UPDATE role SET delete_flag = 1 , update_time = CURRENT_TIMESTAMP(6) where delete_flag = 0 and role_id in ( ? )
	 */
	public java.util.List<String> deleteByRoleIds(java.util.List<String> roleIds) throws DataAccessException;
	

}



