spring:
  application:
    name: ${systemName?uncap_first}${projectName?cap_first}
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr:  ${nacos.serverAddr}
        
    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        #port: 8721
        port: ${${systemName?uncap_first}${projectName?cap_first}.sentinel.transport.port}   
        dashboard: ${sentinel.transport.dashboard}   
      # 设置Sentinel Nacos数据源配置
      datasource:
        #其中flow是数据源名，可以自行随意修改
        flow:
          nacos:
            server-addr: ${nacos.serverAddr}        
            data-id: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            # 配置后报错提示：Type 'com.alibaba.cloud.sentinel.datasource.config.NacosDataSourceProperties' has no property 'rule-type' ， 以为哪里配置错了或版本不对， 最后发现忽略即可， 项目可正常启动
            rule-type: FLOW
  
  
  
server:
  port: 8090
   