/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service;

import java.util.List;
import org.stategen.framework.lite.PageList;

import ${packageName}.domain.RoleMenu;

/**
 * RoleMenuServiceFacade
 * <pre>
 * database table: role_menu
 * database table comments: RoleMenu
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface RoleMenuService extends RoleMenuServiceFacade {

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#insert
     */
    public RoleMenu insert(RoleMenu roleMenu);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#update
     */
    public RoleMenu update(RoleMenu roleMenu);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenuById
     */
    public RoleMenu getRoleMenuById(Long id);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenuPageListByDefaultQuery
     */
    public PageList<RoleMenu> getRoleMenuPageListByDefaultQuery(RoleMenu roleMenu, int pageSize, int pageNum);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenusByIds
     */
    public List<RoleMenu> getRoleMenusByIds(java.util.List<Long> ids);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#deleteByIds
     */
    public List<Long> deleteByIds(java.util.List<Long> ids);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenusByMenuIds
     */
    public List<RoleMenu> getRoleMenusByMenuIds(java.util.List<Long> menuIds);

    /*** 保存roleMenu,有id时更新，没有id时插入,并带回新的id，返回 roleMenu*/
    public RoleMenu saveRoleMenu(RoleMenu roleMenu);

    /*** 批量保存roleMenus,有id时更新，没有id时插入,并带回新的id，返回 roleMenus*/
    public List<RoleMenu> saveRoleMenus(List<RoleMenu> roleMenus);

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#delete
     */
    public Long delete(Long id);
}
