/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service;

import java.util.List;
import org.stategen.framework.lite.PageList;

import ${packageName}.domain.User;

/**
 * UserServiceFacade
 * <pre>
 * database table: user
 * database table comments: User
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface UserService extends UserServiceFacade {

    /*** 保存user,有id时更新，没有id时插入,并带回新的id，返回 user*/
    public User saveUser(User user);

    /*** 批量保存users,有id时更新，没有id时插入,并带回新的id，返回 users*/
    public List<User> saveUsers(List<User> users);

    /**
     * 
     * @see ${packageName}.dao.UserDao#insert
     */
    public User insert(User user);

    /**
     * 
     * @see ${packageName}.dao.UserDao#deleteByUserId
     */
    public Long deleteByUserId(String userId);

    /**
     * 
     * @see ${packageName}.dao.UserDao#deleteByEmail
     */
    public Long deleteByEmail(String email);

    /**
     * 
     * @see ${packageName}.dao.UserDao#update
     */
    public User update(User user);

    /**
     * 
     * @see ${packageName}.dao.UserDao#getUserByUserId
     */
    public User getUserByUserId(String userId);

    /**
     * 
     * @see ${packageName}.dao.UserDao#getUserByEmail
     */
    public User getUserByEmail(String email);

    /**
     * 
     * @see ${packageName}.dao.UserDao#getUserPageListByDefaultQuery
     */
    public PageList<User> getUserPageListByDefaultQuery(User user, int pageSize, int pageNum);

    /**
     * 
     * @see ${packageName}.dao.UserDao#getUsersByUserIds
     */
    public List<User> getUsersByUserIds(java.util.List<String> userIds);

    /**
     * 
     * @see ${packageName}.dao.UserDao#getUsersByEmails
     */
    public List<User> getUsersByEmails(java.util.List<String> emails);

    /**
     * 
     * @see ${packageName}.dao.UserDao#deleteByUserIds
     */
    public Long deleteByUserIds(java.util.List<String> userIds);

    /**
     * 
     * @see ${packageName}.dao.UserDao#deleteByEmails
     */
    public Long deleteByEmails(java.util.List<String> emails);

    /**
     * 
     * @see ${packageName}.dao.UserDao#login
     */
    public User login(String username, String password);

    /**
     * 
     * @see ${packageName}.dao.UserDao#getUsers
     */
    public PageList<User> getUsers(String address, java.util.Date beginDate, java.util.Date endDate, int pageSize, int pageNum);

    /**
     * 
     * @see ${packageName}.dao.UserDao#deleteByIds
     */
    public Long deleteByIds(java.util.List<String> userIds);
}
