/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.domain;

import java.text.SimpleDateFormat;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;

import org.stategen.framework.lite.IMenu;
import org.stategen.framework.lite.TreeNode;
import org.stategen.framework.lite.enums.MenuType;
import org.stategen.framework.lite.enums.VisitCheckType;

import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModelProperty;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
 * Menu
 * <pre>
 * database table: menu
 * database table comments: Menu
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgen生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 不建议使@Data,其hashCode有问题
 * </pre>
 */
@Getter
@Setter
@NoArgsConstructor
@Accessors(chain = true)
public class Menu extends TreeNode<Menu> implements java.io.Serializable, IMenu<Menu> {

    private String roleId;

    private Boolean checked;

    private static final long serialVersionUID = -5216457518046898601L;

    /**
     * Getter method for property <tt>id id</tt>.
     * @return property value of id id
     */
    @ApiModelProperty("id,和MenuId相同，为了生成树")
    public Long getId() {
        return getMenuId();
    }

    public List<Menu> getMenuChildren() {
        return super.getChildren();
    }

    @ApiModelProperty(value = "打开顺序，前端model存储用", hidden = true)
    public Integer getOpendOrder() {
        return null;
    }
}
