/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service.impl;

import java.util.List;

import javax.annotation.Resource;
import org.stategen.framework.lite.PageList;

import ${packageName}.dao.RoleMenuDao;
import ${packageName}.domain.RoleMenu;
import ${packageName}.service.RoleMenuService;

/**
 * RoleMenuServiceImpl
 * <pre>
 * database table: role_menu
 * database table comments: RoleMenu
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class RoleMenuServiceImpl implements RoleMenuService {

    @Resource(name = "roleMenuDao")
    RoleMenuDao roleMenuDao;

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#insert
     * @see ${packageName}.service.RoleMenuService#insert
     */
    @Override
    public RoleMenu insert(RoleMenu roleMenu) {
        return roleMenuDao.insert(roleMenu);
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#update
     * @see ${packageName}.service.RoleMenuService#update
     */
    @Override
    public RoleMenu update(RoleMenu roleMenu) {
        return roleMenuDao.update(roleMenu);
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenuById
     * @see ${packageName}.service.RoleMenuService#getRoleMenuById
     */
    @Override
    public RoleMenu getRoleMenuById(Long id) {
        return roleMenuDao.getRoleMenuById(id);
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenuPageListByDefaultQuery
     * @see ${packageName}.service.RoleMenuService#getRoleMenuPageListByDefaultQuery
     */
    @Override
    public PageList<RoleMenu> getRoleMenuPageListByDefaultQuery(RoleMenu roleMenu, int pageSize, int pageNum) {
        return roleMenuDao.getRoleMenuPageListByDefaultQuery(roleMenu, pageSize, pageNum);
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenusByIds
     * @see ${packageName}.service.RoleMenuService#getRoleMenusByIds
     */
    @Override
    public List<RoleMenu> getRoleMenusByIds(java.util.List<Long> ids) {
        return roleMenuDao.getRoleMenusByIds(ids);
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#deleteByIds
     * @see ${packageName}.service.RoleMenuService#deleteByIds
     */
    @Override
    public List<Long> deleteByIds(java.util.List<Long> ids) {
        return roleMenuDao.deleteByIds(ids);
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#getRoleMenusByMenuIds
     * @see ${packageName}.service.RoleMenuService#getRoleMenusByMenuIds
     */
    @Override
    public List<RoleMenu> getRoleMenusByMenuIds(java.util.List<Long> menuIds) {
        return roleMenuDao.getRoleMenusByMenuIds(menuIds);
    }

    /*** 保存roleMenu,有id时更新，没有id时插入,并带回新的id，返回 roleMenu*/
    @Override
    public RoleMenu saveRoleMenu(RoleMenu roleMenu) {
        if (roleMenu != null) {
            java.lang.Long id = roleMenu.getId();
            if (id != null) {
                insert(roleMenu);
            } else {
                update(roleMenu);
            }
        }
        return roleMenu;
    }

    /*** 批量保存roleMenus,有id时更新，没有id时插入,并带回新的id，返回 roleMenus*/
    @Override
    public List<RoleMenu> saveRoleMenus(List<RoleMenu> roleMenus) {
        for (RoleMenu roleMenu : roleMenus) {
            this.saveRoleMenu(roleMenu);
        }
        return roleMenus;
    }

    /**
     * 
     * @see ${packageName}.dao.RoleMenuDao#delete
     * @see ${packageName}.service.RoleMenuService#delete
     */
    @Override
    public Long delete(Long id) {
        return roleMenuDao.delete(id);
    }
}
