/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.domain;

import java.text.SimpleDateFormat;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import org.stategen.framework.lite.IOption;

import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModelProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * Province
 * <pre>
 * database table: province
 * database table comments: Province
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgen生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 不建议使@Data,其hashCode有问题
 * </pre>
 */
@Getter
@Setter
public class Province implements java.io.Serializable, IOption {

    private static final long serialVersionUID = -5216457518046898601L;

    /***provinceId   db_column: province_id VARCHAR */
    @ApiModelProperty("provinceId")
    @Id
    @Max(64)
    private String provinceId;

    /***name   db_column: name VARCHAR */
    @ApiModelProperty("name")
    @Max(100)
    private String name;

    /***pycode   db_column: pycode VARCHAR */
    @ApiModelProperty("pycode")
    @Max(50)
    private String pycode;

    /***创建时间   db_column: create_time TIMESTAMP */
    @ApiModelProperty(value = "创建时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date createTime;

    /***更新时间   db_column: update_time TIMESTAMP */
    @ApiModelProperty(value = "更新时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date updateTime;

    /***是否删除(0:正常，1删除)   db_column: delete_flag INTEGER */
    @ApiModelProperty(value = "是否删除(0:正常，1删除)", hidden = true)
    private Integer deleteFlag;

    /*----------------getter & setter ignore by lombok -------------------*/
    public String toString() {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd H:m:ss.SSS");
        StringBuffer sb = new StringBuffer(1024);
        sb.append('{');
        sb.append("provinceIds=").append(provinceIds).append('\n');
        sb.append("nameLike=").append(nameLike).append('\n');
        sb.append("pycodeLike=").append(pycodeLike).append('\n');
        sb.append("createTimeMin=").append(createTimeMin != null ? df.format(createTimeMin) : null).append('\n');
        sb.append("createTimeMax=").append(createTimeMax != null ? df.format(createTimeMax) : null).append('\n');
        sb.append("updateTimeMin=").append(updateTimeMin != null ? df.format(updateTimeMin) : null).append('\n');
        sb.append("updateTimeMax=").append(updateTimeMax != null ? df.format(updateTimeMax) : null).append('\n');
        sb.append("provinceId=").append(provinceId).append('\n');
        sb.append("name=").append(name).append('\n');
        sb.append("pycode=").append(pycode).append('\n');
        sb.append("createTime=").append(createTime != null ? df.format(createTime) : null).append('\n');
        sb.append("updateTime=").append(updateTime != null ? df.format(updateTime) : null).append('\n');
        sb.append("deleteFlag=").append(deleteFlag);
        sb.append('}');
        return sb.toString();
    }

    /*** provinceIds in getProvincePageList */
    @ApiModelProperty("provinceId s")
    @JSONField(serialize = false)
    private java.util.List<String> provinceIds;

    /*** nameLike in getProvincePageList */
    @ApiModelProperty("nameLike")
    @JSONField(serialize = false)
    private String nameLike;

    /*** pycodeLike in getProvincePageList */
    @ApiModelProperty("pycodeLike")
    @JSONField(serialize = false)
    private String pycodeLike;

    /*** 创建时间Min in getProvincePageList */
    @ApiModelProperty("创建时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date createTimeMin;

    /*** 创建时间Max in getProvincePageList */
    @ApiModelProperty("创建时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date createTimeMax;

    /*** 更新时间Min in getProvincePageList */
    @ApiModelProperty("更新时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date updateTimeMin;

    /*** 更新时间Max in getProvincePageList */
    @ApiModelProperty("更新时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date updateTimeMax;

    @Override
    public String getTitle() {
        if (name != null) {
            return name;
        }
        return null;
    }

    @Override
    public String getValue() {
        if (provinceId != null) {
            return provinceId;
        }
        return null;
    }
}
