/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.domain;

import java.text.SimpleDateFormat;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;

import org.stategen.framework.annotation.OptionConvertor;
import org.stategen.framework.lite.IOption;

import com.alibaba.fastjson.annotation.JSONField;
import ${packageName}.enums.RegionType;
import io.swagger.annotations.ApiModelProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * Region
 * <pre>
 * database table: region
 * database table comments: Region
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgen生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 不建议使@Data,其hashCode有问题
 * </pre>
 */
@Getter
@Setter
@OptionConvertor(parentId = "parentRegionId", label = "name")
public class Region implements java.io.Serializable, IOption {

    private Boolean isLeaf;

    private static final long serialVersionUID = -5216457518046898601L;


    @Override
    public String getTitle() {
        return getName();
    }

    @Override
    public String getValue() {
        if (regionId == null) {
            return null;
        }
        return regionId.toString();
    }
}
