/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.domain;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Email;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;

import org.stategen.framework.annotation.ChangeBy;
import org.stategen.framework.annotation.Editor;
import org.stategen.framework.annotation.ReferConfig;
import org.stategen.framework.lite.enums.EditorType;

import com.alibaba.fastjson.annotation.JSONField;
import ${packageName}.enums.RoleType;
import ${packageName}.enums.StatusEnum;
import io.swagger.annotations.ApiModelProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * User
 * <pre>
 * database table: user
 * database table comments: User
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgen生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 不建议使@Data,其hashCode有问题
 * </pre>
 */
@Getter
@Setter
public class User implements java.io.Serializable {

    @ApiModelProperty("用户可访问的节点")
    @JSONField(serialize = false)
    private List<Long> visitsIds;

    private Province province;

    private City city;

    //注意，cascaderPostAddresss 不是 cascaderPostAddress
    private List<Region> cascaderPostAddresss;

    private List<Hoppy> hoppys;

    //用id存储到表中
    @ReferConfig
    @Editor(EditorType.CheckboxGroup.class)
    @ApiModelProperty("爱好 ids")
    private List<Long> hoppyIds;

    /***头像   db_column: avatar_img VARCHAR */
    @ApiModelProperty("头像")
    @Max(255)
    private FileSummary avatarImg;

    private static final long serialVersionUID = -5216457518046898601L;


    @Editor(value = EditorType.Cascader.class)
    @ReferConfig(optionClass = Region.class)
    @ApiModelProperty("邮寄地址")
    public List<Long> getCascaderPostAddressIds() {
        if (this.cascaderPostAddresss != null) {
            List<Long> result = new ArrayList<Long>(cascaderPostAddresss.size());
            for (Region region : cascaderPostAddresss) {
                result.add(region.getRegionId());
            }
            return result;
        }
        return null;
    }
}
