/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignService;

import ${packageName}.domain.FileSummary;

/**
 * FileSummaryService
 * <pre>
 * database table: upload_file
 * database table comments: FileSummary
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface FileSummaryService extends AssignService<FileSummary, String>, FileSummaryService${systemName?cap_first} {

    String getProjectName();

    //<#--
    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#insert
     */
    public FileSummary insert(FileSummary fileSummary);

    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#delete
     */
    public String delete(String fileId);

    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#update
     */
    public FileSummary update(FileSummary fileSummary);

    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#getFileSummaryByFileId
     */
    public FileSummary getFileSummaryByFileId(String fileId);

    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#getFileSummaryPageList
     */
    public PageList<FileSummary> getFileSummaryPageList(FileSummary fileSummary, int pageSize, int pageNum);

    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#getFileSummarysByFileIds
     */
    public List<FileSummary> getFileSummarysByFileIds(java.util.List<String> fileIds);

    /**
     * 
     * @see ${packageName}.dao.FileSummaryDao#deleteByFileIds
     */
    public java.util.List<String> deleteByFileIds(java.util.List<String> fileIds);

    /*** 保存fileSummary,有id时更新，没有id时插入,并带回新的id，返回 fileSummary
     * @see ${packageName}.dao.FileSummaryDao#insert
     */
    public FileSummary saveFileSummary(FileSummary fileSummary);

    /** 批量保存fileSummarys,有id时更新，没有id时插入,并带回新的id，返回 fileSummarys
     * @see ${packageName}.dao.FileSummaryDao#insert
     */
    public List<FileSummary> saveFileSummarys(List<FileSummary> fileSummarys);
    // -->
    //
}
