/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package ${packageName}.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignSerice;

import ${packageName}.domain.Menu;
import ${packageName}.domain.Role;

/**
 * RoleServiceFacade
 * <pre>
 * database table: role
 * database table comments: Role
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface RoleService extends AssignSerice<Role, String>, RoleService${systemName?cap_first} {

    public List<Menu> getAllMenusWithRoleChecked(String roleId);
	
    //<#--
    /*** 保存role,有id时更新，没有id时插入，返回 role*/
    public Role saveRole(Role role);

    /*** 批量保存roles,有id时更新，没有id时插入,并带回新的id，返回 roles*/
    public List<Role> saveRoles(List<Role> roles);


    /**
     * 
     * @see ${packageName}.dao.RoleDao#insert
     */
    public Role insert(Role role);

    /**
     * 
     * @see ${packageName}.dao.RoleDao#update
     */
    public Role update(Role role);

    /**
     * 
     * @see ${packageName}.dao.RoleDao#getRoleByRoleId
     */
    public Role getRoleByRoleId(String roleId);

    /**
     * 
     * @see ${packageName}.dao.RoleDao#getRolesByRoleIds
     */
    public List<Role> getRolesByRoleIds(java.util.List<String> roleIds);

    /**
     * 
     * @see ${packageName}.dao.RoleDao#delete
     */
    public String delete(String roleId);

    /**
     * 
     * @see ${packageName}.dao.RoleDao#deleteByRoleIds
     */
    public List<String> deleteByRoleIds(java.util.List<String> roleIds);

    /**
     * 
     * @see ${packageName}.dao.RoleDao#getRolePageList
     */
    public PageList<Role> getRolePageList(Role role, int pageSize, int pageNum);
    //-->
    //
}
