/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package ${packageName}.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignSerice;

import ${packageName}.domain.Topic;

/**
 * TopicService
 * <pre>
 * database table: topic
 * database table comments: Topic
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface TopicService extends AssignSerice<Topic, String>, TopicService${systemName?cap_first} {

    void assignTopicExtraProperties(List<Topic> topics);

    //<#--
    /**
     * 
     * @see ${packageName}.dao.TopicDao#insert
     */
    public Topic insert(Topic topic);

    /**
     * 
     * @see ${packageName}.dao.TopicDao#delete
     */
    public String delete(String topicId);

    /**
     * 
     * @see ${packageName}.dao.TopicDao#update
     */
    public Topic update(Topic topic);

    /**
     * 
     * @see ${packageName}.dao.TopicDao#getTopicByTopicId
     */
    public Topic getTopicByTopicId(String topicId);

    /**
     * 
     * @see ${packageName}.dao.TopicDao#getTopicsByTopicIds
     */
    public List<Topic> getTopicsByTopicIds(java.util.List<String> topicIds);

    /**
     * 
     * @see ${packageName}.dao.TopicDao#deleteByTopicIds
     */
    public java.util.List<String> deleteByTopicIds(java.util.List<String> topicIds);

    /*** 保存topic,有id时更新，没有id时插入,并带回新的id，返回 topic
     * @see ${packageName}.dao.TopicDao#insert
     */
    public Topic saveTopic(Topic topic);

    /** 批量保存topics,有id时更新，没有id时插入,并带回新的id，返回 topics
     * @see ${packageName}.dao.TopicDao#insert
     */
    public List<Topic> saveTopics(List<Topic> topics);

    /**
     * 
     * @see ${packageName}.dao.TopicDao#getTopicPageList
     */
    public PageList<Topic> getTopicPageList(Topic topic, int pageSize, int pageNum);

    /**
     * 获取当前回复的数量
     * @see ${packageName}.dao.TopicDao#getReplyCounts
     */
    public List<Topic> getReplyCounts(java.util.List<String> topicIds);
    //-->
    //
}
