/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignSerice;

import com.mycompany.biz.domain.TopicReply;

/**
 * TopicReplyService
 * <pre>
 * database table: topic_reply
 * database table comments: TopicReply
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface TopicReplyService extends AssignSerice<TopicReply, String>, TopicReplyServiceTrade {

    TopicReply replyUp(String replyId, String authorId);

    void assignRepliesExtraProperties(String authorId, List<TopicReply> replies);

    //<#--
    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#insert
     */
    public TopicReply insert(TopicReply topicReply);

    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#delete
     */
    public String delete(String replyId);

    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#update
     */
    public TopicReply update(TopicReply topicReply);

    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#getTopicReplyByReplyId
     */
    public TopicReply getTopicReplyByReplyId(String replyId);

    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#getTopicReplysByReplyIds
     */
    public List<TopicReply> getTopicReplysByReplyIds(java.util.List<String> replyIds);

    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#deleteByReplyIds
     */
    public java.util.List<String> deleteByReplyIds(java.util.List<String> replyIds);

    /*** 保存topicReply,有id时更新，没有id时插入,并带回新的id，返回 topicReply*/
    public TopicReply saveTopicReply(TopicReply topicReply);

    /*** 批量保存topicReplys,有id时更新，没有id时插入,并带回新的id，返回 topicReplys*/
    public List<TopicReply> saveTopicReplys(List<TopicReply> topicReplys);

    /**
     * 
     * @see com.mycompany.biz.dao.TopicReplyDao#getTopicReplyPageList
     */
    public PageList<TopicReply> getTopicReplyPageList(TopicReply topicReply, String authorId, int pageSize, int pageNum);
    //-->
    //
}
